sudo: false
language: clojure
jdk:
- openjdk11

install: true

before_install:
  - sed --in-place "s|:creds :gpg|:username \"yleisradio-travis-ci\" :password :env/github_token|" project.clj

script:
- lein do spec, lint

cache:
  directories:
  - "$HOME/.m2"
