name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-lein-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-lein-

      - name: Set environment
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          sed --in-place "s|:creds :gpg|:username \"yleisradio-travis-ci\" :password :env/npm_token|" project.clj

      - name: Make test
        run: |
          java -version
          lein do spec, lint

